#
# References
# - https://github.com/zurfyx/travis-android

#
git:
  submodules: false
  depth: 3

notifications:
  email:
    - luncliff@gmail.com

cache:
  directories:
    - $HOME/.gradle/caches/

os: linux
dist: xenial
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - tree
      - ninja-build
      - curl
      - wget

language: android
android:
  components: # Android SDK Manager
    - tools
    - platform-tools
    - android-30
    - build-tools-30.0.3
  licenses:
    - "android-sdk-license-.+"
    - "google-gdk-license-.+"

before_install:
  # forced upgrade of CMake
  - sudo rm -rf /usr/local/cmake-*
  - mkdir -p build && pushd build
  - wget -q https://cmake.org/files/v3.20/cmake-3.20.0-Linux-x86_64.tar.gz
  - tar -xvf ./cmake-3.20.0-Linux-x86_64.tar.gz > /dev/null
  - sudo mv cmake-3.20.0-Linux-x86_64/bin/* /usr/bin/
  - sudo mv cmake-3.20.0-Linux-x86_64/share/cmake-3.20 /usr/share/cmake-3.20
  - popd
  - cmake --version && which cmake

install:
  # Android NDK
  - bash ./scripts/travis-ci.sh "ndk;21.3.6528147"
  - bash ./scripts/travis-ci.sh "ndk;22.1.7171670"
  # Gradle
  - curl -s "https://get.sdkman.io" | bash > /dev/null
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk version
  - sdk install gradle

script:
  - gradle clean
  - gradle androidDependencies
  - gradle assembleDebug
  - gradle assembleRelease assemble

after_success:
  - tree ./build/intermediates/cmake/debug/obj
  - tree ./build/intermediates/cmake/release/obj
  - tree ./build/outputs/aar
