# ---------------------------------------------------------------------------
#
#   Author
#     - luncliff@gmail.com
#
# ---------------------------------------------------------------------------
sudo: false

git:
  submodules: true
  depth: 3

notifications:
  email:
    - luncliff@gmail.com

language: android
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ninja-build
      - cmake
      - tree
      - wget
      - unzip
android:
  components:
    - tools
    - platform-tools
    - android-25 # 7.0
    - android-27 # 8.1
    - android-28 # 9.0
    - build-tools-28.0.3
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  # Install CMake 3.14.1 (build.gradle requires the exact version)
  - wget -q https://github.com/Kitware/CMake/releases/download/v3.14.1/cmake-3.14.1-Linux-x86_64.tar.gz
  - tar -xf cmake-3.14.1-Linux-x86_64.tar.gz
  - pushd ./cmake-3.14.1-Linux-x86_64
  - sudo mv ./bin/*      /usr/local/bin
  - sudo mv ./share/*   /usr/local/share
  - popd
  # Install Gradle from https://sdkman.io/
  - curl -s "https://get.sdkman.io" | bash > /dev/null
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk version
  - sdk install gradle
  - sdk use gradle
  - gradle --version
install:
  # Accept SDK Licenses + Install NDK
  - yes | sdkmanager --update > /dev/null 2>&1
  - sdkmanager ndk-bundle > /dev/null 2>&1
script:
  - gradle clean
  - gradle assemble -warning-mode all
after_success:
  - tree ./install
