#
#   Author: luncliff@gmail.com
#

trigger:
  branches:
    exclude:
      - docs
      - gh-pages

jobs:
  - job: build_check_0
    pool:
      vmImage: "macOS-latest"
    steps:
      - checkout: self
        submodules: true
      - task: CmdLine@2
        inputs:
          script: |
            brew install ninja
            brew info cmake
            gradle --version
            gradle wrapper
        displayName: "Check Environment"
      - task: Gradle@2
        inputs:
          gradleWrapperFile: "gradlew"
          publishJUnitResults: false
          gradleOptions: "-Xmx3072m"
          tasks: "androidDependencies"
          options: "--info"
        displayName: "Gradle: androidDependencies"
      - task: Gradle@2
        inputs:
          gradleWrapperFile: "gradlew"
          publishJUnitResults: false
          checkStyleRunAnalysis: true
          gradleOptions: "-Xmx3072m"
          tasks: "assemble"
          options: "--info"
        displayName: "Gradle: assemble"
      - task: CopyFiles@2
        inputs:
          contents: "build/outputs/aar/*.apk"
          targetFolder: "$(build.artifactStagingDirectory)"
      - task: PublishBuildArtifacts@1
