#
# References
#   - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops
#
variables:
  VCPKG_FEATURE_FLAGS: "versions,manifests,registries,binarycaching"

jobs:
  - job: build_check_0
    pool:
      vmImage: "macOS-latest"
    variables:
      VCPKG_ROOT: "/usr/local/share/vcpkg" # check $VCPKG_INSTALLATION_ROOT
      ANDROID_NDK_HOME: "/Users/runner/Library/Android/sdk/ndk/22.1.7171670" # see scripts/azure-pipelines.sh, check $ANDROID_SDK_ROOT
    steps:
      - checkout: self
      - script: env
        displayName: "Report: Environment Variables"
      - task: CmdLine@2
        inputs:
          script: |
            brew install ninja
            brew install tree
            pushd ${VCPKG_ROOT}
              pushd triplets/community
                wget https://raw.githubusercontent.com/luncliff/vcpkg-registry/main/triplets/arm64-android.cmake
                wget https://raw.githubusercontent.com/luncliff/vcpkg-registry/main/triplets/arm-android.cmake
                wget https://raw.githubusercontent.com/luncliff/vcpkg-registry/main/triplets/x64-android.cmake
              popd
              tree -L 2 $(pwd)/triplets
            popd
        displayName: "Setup: Homebrew/Vcpkg"
      - task: CmdLine@2
        inputs:
          script: |
            brew uninstall cmake
            bash ./scripts/azure-pipelines.sh > /dev/null
        displayName: "Setup: Android SDK"
      - task: CmdLine@2
        inputs:
          script: |
            gradle --version
            gradle wrapper
        displayName: "Gradle: wrapper"
      - task: Gradle@2
        inputs:
          gradleWrapperFile: "gradlew"
          publishJUnitResults: false
          gradleOptions: "-Xmx3072m"
          tasks: "androidDependencies"
          options: "--info"
        displayName: "Gradle: androidDependencies"
      - task: Gradle@2
        inputs:
          gradleWrapperFile: "gradlew"
          publishJUnitResults: false
          checkStyleRunAnalysis: true
          gradleOptions: "-Xmx3072m"
          tasks: "assembleDebug"
          options: "--info"
        displayName: "Gradle: assembleDebug"
      - task: Gradle@2
        inputs:
          gradleWrapperFile: "gradlew"
          publishJUnitResults: false
          checkStyleRunAnalysis: true
          gradleOptions: "-Xmx3072m"
          tasks: "assemble"
          options: "--warning-mode all"
        displayName: "Gradle: assemble"
      - task: CopyFiles@2
        inputs:
          contents: "$(Build.SourcesDirectory)/build/outputs/aar/*.aar"
          targetFolder: "$(build.artifactStagingDirectory)"
      - task: PublishBuildArtifacts@1

trigger:
  branches:
    exclude:
      - docs
      - gh-pages

schedules:
  - cron: "0 3 * * 0"
    displayName: "Weekly Build"
    branches:
      include:
        - master
        - support/*
      exclude:
        - docs
        - gh-pages
    always: true
