# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  vmImage: 'macOS 10.13'

# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/java?view=vsts#build-your-code-with-gradle
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/android?view=vsts
steps:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts#checkout
- checkout: self  
  fetchDepth: 2
  submodules: true
- script: gradle wrapper
  displayName: 'Make Gradlew'
- task: Gradle@2 
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    tasks: 'assemble'
