#
# References
#   - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops
#
variables:
  VCPKG_FEATURE_FLAGS: "versions,manifests,registries,binarycaching"

jobs:
  - job: build_check_0
    pool:
      vmImage: "macOS-latest"
    variables:
      VCPKG_TOOLCHAIN_FILE: value1
    steps:
      - checkout: self
        submodules: true
      - task: CmdLine@2
        inputs:
          script: |
            env
            brew install ninja
            brew uninstall cmake
            bash ./scripts/azure-pipelines.sh
            gradle --version
            gradle wrapper
        displayName: "Check Environment"
      - task: Gradle@2
        inputs:
          gradleWrapperFile: "gradlew"
          publishJUnitResults: false
          gradleOptions: "-Xmx3072m"
          tasks: "androidDependencies"
          options: "--info"
        displayName: "Gradle: androidDependencies"
      - task: Gradle@2
        inputs:
          gradleWrapperFile: "gradlew"
          publishJUnitResults: false
          checkStyleRunAnalysis: true
          gradleOptions: "-Xmx3072m"
          tasks: "assemble"
          options: "--warning-mode all"
        displayName: "Gradle: assemble"
      - task: CopyFiles@2
        inputs:
          contents: "$(Build.SourcesDirectory)/build/outputs/aar/*.aar"
          targetFolder: "$(build.artifactStagingDirectory)"
      - task: PublishBuildArtifacts@1

trigger:
  branches:
    exclude:
      - docs
      - gh-pages

schedules:
  - cron: "0 3 * * 0"
    displayName: "Weekly Build"
    branches:
      include:
        - master
        - support/*
      exclude:
        - docs
        - gh-pages
    always: true
