#
#   Author: luncliff@gmail.com
#

trigger:
  branches:
    exclude:
      - docs

jobs:
  - job: macosx_gradle
    pool:
      vmImage: macos-latest

    steps:
      - checkout: self
        submodules: true

      - task: CmdLine@2
        inputs:
          script: |
            brew install ninja
            brew info cmake
        displayName: "Homebrew"

      - task: CmdLine@2
        inputs:
          script: |
            gradle --version
            gradle wrapper
        displayName: "Make Gradle Wrapper"

      - task: Gradle@2
        inputs:
          workingDirectory: ""
          gradleWrapperFile: "gradlew"
          gradleOptions: "-Xmx3072m"
          tasks: "clean"

      - task: Gradle@2
        inputs:
          workingDirectory: ""
          gradleWrapperFile: "gradlew"
          gradleOptions: "-Xmx3072m"
          tasks: "assemble"
