message(STATUS "---------- ${PROJECT_NAME} : ${PROJECT_VERSION} --------------------")

message(STATUS "System      \t: ${CMAKE_SYSTEM}")
message(STATUS "Build Type  \t: ${CMAKE_BUILD_TYPE}")
message(STATUS)
message(STATUS "Path")
message(STATUS "  Root      \t: ${CMAKE_SOURCE_DIR}")
message(STATUS "  Project   \t: ${PROJECT_SOURCE_DIR}")
message(STATUS "  Install   \t: ${CMAKE_INSTALL_PREFIX}")
message(STATUS "  Current   \t: ${CMAKE_CURRENT_SOURCE_DIR}")
message(STATUS)
message(STATUS "CMake")
message(STATUS "  Version   \t: ${CMAKE_VERSION}")
message(STATUS "  Toolchain \t: ${CMAKE_TOOLCHAIN_FILE}")
message(STATUS "  Path      \t: ${CMAKE_COMMAND}")
if(DEFINED VCPKG_CHAINLOAD_TOOLCHAIN_FILE)
message(STATUS "VcPkg")
message(STATUS "  Path      \t: ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
message(STATUS "  Chainload \t: ${VCPKG_CHAINLOAD_TOOLCHAIN_FILE}")
endif()
message(STATUS)
message(STATUS "Compiler")
message(STATUS "  ID        \t: ${CMAKE_CXX_COMPILER_ID}")
message(STATUS "  Version   \t: ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "  Path      \t: ${CMAKE_CXX_COMPILER}")
message(STATUS)
message(STATUS "Android")
message(STATUS "  Platform  \t: ${ANDROID_PLATFORM}")     # API level
message(STATUS "  Arch      \t: ${ANDROID_ARCH_NAME}")    # 
message(STATUS "  ABI       \t: ${ANDROID_ABI}")          # 
message(STATUS "  NDK       \t: ${ANDROID_NDK}")          # Path/to/NDK
message(STATUS "  STL       \t: ${ANDROID_STL}")          # expect c++_shared
message(STATUS)
if(ANDROID_ABI MATCHES "arm")
message(STATUS "ARM")
message(STATUS "  Mode      \t: ${ANDROID_ARM_MODE}")
message(STATUS "  Neon      \t: ${ANDROID_ARM_NEON}")
endif()
